from declaring_mapping import Customers
from creating_sessions import session
from sqlalchemy import and_,or_

# filtered_obj=session.query(Customers).filter(Customers.id>3)
# filtered_obj=session.query(Customers).filter(Customers.id==3)
# filtered_obj=session.query(Customers).filter(Customers.id!=3)
# filtered_obj=session.query(Customers).filter(Customers.last_name.like('%s'))
# filtered_obj=session.query(Customers).filter(Customers.fname.startswith('m'))
# filtered_obj=session.query(Customers).filter(Customers.id.in_([2,5]))
#AND
#This conjunction is generated by either putting multiple commas separated criteria in the filter or using and_() method
# filtered_obj=session.query(Customers).filter(Customers.id>3,Customers.last_name.like('%ie%'))
# filtered_obj=session.query(Customers).filter(and_(Customers.id>3,Customers.last_name.like('%ie%')))
# OR
filtered_obj=session.query(Customers).filter(or_(Customers.id==7,Customers.id==17,Customers.last_name.like('%ie%')))

for obj in filtered_obj:
    print('firstname:',obj.fname,'last:',obj.last_name,'email:',obj.email_address)